name: logs
version: 0.0.2

description: Lightweight logging for Dart.
homepage: https://github.com/pq/logs

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.2
